#source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'SwiftyBehavior_Example' do
    
    pod 'SwiftyBehavior', :path => '../'
    
    target 'SwiftyBehavior_Tests' do
        inherit! :search_paths
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "2.3"
            
        end
    end
end
